version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
  dummy-node-app:
    image: mcheli/dummy-node-app
    depends_on: 
      - db
    environment:
      - VIRTUAL_HOST=dummy.localhost
      - DATABASE_HOST=db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080